Add workaround for crates with rust-toolchain and test it (#22)
* Add test against crates with rust-toolchain

This test crashes as of now and will be fixed in the next commit:
```
trawling source code of dependencies for unsafety
    Checking bitvec v0.15.2
    Checking crate-uses-rust-toolchain v0.1.0 (/Users/dc/tob/projects/siderophile/tests/crate-use-rust-toolchain)
  1 // This program tests if we can use Siderophile with crates which dependencies
error[E0463]: can't find crate for `bitvec`                              ] 1/2: crate-uses-rust-toolchain
 --> src/lib.rs:9:1
  |
9 | extern crate bitvec;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cargo("Could not compile `crate-uses-rust-toolchain`.")', src/libcore/result.rs:1187:5
```

* Add workaround for crates with rust-toolchain file

There is an option to specify `rust-toolchain` file for your crate,
to tell cargo which toolchain version to use.

Normal builds via `cargo build` compiles the crate and its dependencies with
one toolchain version and so does not respect dependencies
`rust-toolchain` files.

However, Siderophile somehow compiles packages one by one and do indeed
respect the `rust-toolchain` file, leading to compiling dependencies
with wrong toolchain versions (if they are installed) or not compiling
them at all. In the end this ends up failing the compilation (no matter
if the depedency was compiled with wrong toolchain version) and so
Siderophile fails to do its job.

This commit adds a workaround for this issue by simply specifying the
`RUSTUP_TOOLCHAIN` environment variable that overrides the toolchain
version with the default one present in the system.

See more information on https://github.com/trailofbits/siderophile/issues/14