Add test against crates with rust-toolchain
This test crashes as of now and will be fixed in the next commit:
```
trawling source code of dependencies for unsafety
    Checking bitvec v0.15.2
    Checking crate-uses-rust-toolchain v0.1.0 (/Users/dc/tob/projects/siderophile/tests/crate-use-rust-toolchain)
  1 // This program tests if we can use Siderophile with crates which dependencies
error[E0463]: can't find crate for `bitvec`                              ] 1/2: crate-uses-rust-toolchain
 --> src/lib.rs:9:1
  |
9 | extern crate bitvec;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cargo("Could not compile `crate-uses-rust-toolchain`.")', src/libcore/result.rs:1187:5
```